# Generated by Django 2.1 on 2019-05-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '出版社表',
            },
        ),
    ]
