# Generated by Django 2.1 on 2019-05-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190516_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='111', max_length=12),
        ),
    ]
