# Generated by Django 2.1 on 2019-05-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20190516_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='username',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='111', max_length=12),
        ),
    ]
