# Generated by Django 2.1 on 2019-05-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20190516_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
